// GTB Vragenrad – Vragenbank
// Design: Playful Professional – Bold Dutch Design
// Vragen zijn ingedeeld in drie niveaus: makkelijk, gemiddeld, moeilijk
// Ze bereiden kandidaten voor op sollicitatiegesprekken én stimuleren zelfreflectie

export type Difficulty = "easy" | "medium" | "hard";

export interface Question {
  id: string;
  text: string;
  difficulty: Difficulty;
  category: string;
  tip?: string; // optionele tip voor de begeleider
  guidance?: string; // optionele duiding: waarom deze vraag en wat is het doel
}

export const easyQuestions: Question[] = [
  {
    id: "e1",
    text: "Hoe zou je jezelf in drie woorden omschrijven?",
    difficulty: "easy",
    category: "Zelfpresentatie",
    tip: "Laat de kandidaat nadenken over positieve eigenschappen die ook relevant zijn voor werk.",
    guidance: "Deze vraag helpt de kandidaat om zichzelf bewust in te schatten en een sterke zelfpresentatie te oefenen. Dit is essentieel voor sollicitatiegesprekken en eerste indrukken op het werk.",
  },
  {
    id: "e2",
    text: "Wat maakt voor jou een werkdag geslaagd?",
    difficulty: "easy",
    category: "Motivatie",
    tip: "Peilt naar wat de kandidaat energie geeft en wat hun definitie van succes is.",
    guidance: "Dit helpt werkgevers begrijpen wat de kandidaat motiveert en wat hun waarden zijn. Goed voor het vinden van een passende werkplek.",
  },
  {
    id: "e3",
    text: "Waar krijg je spontaan energie van op het werk of in je dagelijks leven?",
    difficulty: "easy",
    category: "Motivatie",
    guidance: "Dit helpt de kandidaat en werkgever energiebronnen te identificeren. Essentieel voor duurzame inzetbaarheid en werkplezier.",
  },
  {
    id: "e4",
    text: "Welke vaardigheid krijg je vaak complimenten over?",
    difficulty: "easy",
    category: "Sterktes",
    tip: "Helpt de kandidaat om hun sterke punten te benoemen zonder te bescheiden te zijn.",
    guidance: "Zelfbewustzijn over sterke punten is cruciaal voor zelfvertrouwen in sollicitatiegesprekken en voor het vinden van passende werkrollen.",
  },
  {
    id: "e5",
    text: "Welke taak zou je elke dag kunnen doen zonder je te vervelen?",
    difficulty: "easy",
    category: "Motivatie",
    guidance: "Dit onthult passies en interesses die kunnen helpen bij het vinden van betekenisvol werk dat intrinsieke motivatie oplevert.",
  },
  {
    id: "e6",
    text: "Werk je liever rustig op de achtergrond of sta je graag mee op de voorgrond?",
    difficulty: "easy",
    category: "Werkstijl",
    guidance: "Dit bepaalt of iemand beter past in een ondersteunende rol of een meer zichtbare positie. Belangrijk voor werkplezier en prestaties.",
  },
  {
    id: "e7",
    text: "In welk soort team voel jij je het meest op je gemak?",
    difficulty: "easy",
    category: "Samenwerking",
    guidance: "Teamdynamica beïnvloedt werkplezier en productiviteit. Dit helpt de kandidaat en werkgever de juiste teamcultuur te vinden.",
  },
  {
    id: "e8",
    text: "Op welke realisatie ben je stiekem best trots?",
    difficulty: "easy",
    category: "Sterktes",
    tip: "Moedigt de kandidaat aan om trots te zijn op wat ze bereikt hebben, hoe klein ook.",
    guidance: "Dit helpt de kandidaat hun zelfvertrouwen op te bouwen en hun prestaties te erkennen. Belangrijk voor een positieve zelfbeeld in sollicitatiegesprekken.",
  },
  {
    id: "e9",
    text: "Met welk type collega kan jij het meestal goed vinden?",
    difficulty: "easy",
    category: "Samenwerking",
    guidance: "Dit helpt de kandidaat te begrijpen met welke persoonlijkheidstypes zij goed samenwerkt. Nuttig voor het vinden van een passend team en werksfeer.",
  },
  {
    id: "e10",
    text: "Welke werkplek of omgeving geeft jou meteen een goed gevoel?",
    difficulty: "easy",
    category: "Werkomgeving",
    guidance: "De werkomgeving beïnvloedt prestaties en welzijn sterk. Dit helpt de kandidaat hun ideale werkplek te identificeren en dit met werkgevers te bespreken.",
  },
  {
    id: "e11",
    text: "Ben je eerder een ochtendmens of een avondmens, en merk je dat in je werk?",
    difficulty: "easy",
    category: "Zelfkennis",
    guidance: "Chronotype beïnvloedt productiviteit en welzijn. Dit helpt de kandidaat hun ritme te begrijpen en mogelijke flexibiliteit met werkgevers te bespreken.",
  },
  {
    id: "e12",
    text: "Wat doe je het liefst om te ontspannen na een drukke dag?",
    difficulty: "easy",
    category: "Welzijn",
    guidance: "Dit onthult hoe de kandidaat zichzelf kan herstellen en stress kan beheren. Essentieel voor duurzame inzetbaarheid en werkplezier.",
  },
  {
    id: "e13",
    text: "Welke kleine gewoonte helpt jou om georganiseerd te blijven?",
    difficulty: "easy",
    category: "Organisatie",
    guidance: "Dit toont zelfbewustzijn over persoonlijke werkwijzen en zelfregulatiestrategieën. Nuttig voor het vinden van passende werkstructuren.",
  },
  {
    id: "e14",
    text: "Wat vind je leuk aan samenwerken met anderen?",
    difficulty: "easy",
    category: "Samenwerking",
    guidance: "Dit helpt de kandidaat hun voorkeur voor teamwork te articuleren en wat hen motiveert in samenwerking. Belangrijk voor werkplezier en productiviteit.",
  },
  {
    id: "e15",
    text: "Wat zou een ideale pauze op het werk voor jou bevatten?",
    difficulty: "easy",
    category: "Welzijn",
    guidance: "Dit helpt de kandidaat hun herstelbehoeften te begrijpen en mogelijke aanpassingen met werkgevers te bespreken. Belangrijk voor energiebeheer.",
  },
  {
    id: "e16",
    text: "Met welke drie zaken moet een job voor jou zeker scoren?",
    difficulty: "easy",
    category: "Jobwensen",
    tip: "Geeft inzicht in de prioriteiten van de kandidaat bij het zoeken naar werk.",
    guidance: "Dit helpt de kandidaat hun prioriteiten helder te maken. Essentieel voor het vinden van werk dat echt past bij hun behoeften.",
  },
  {
    id: "e17",
    text: "Welk schoolvak of welke opleiding vond je het meest boeiend, en waarom?",
    difficulty: "easy",
    category: "Achtergrond",
    guidance: "Dit helpt de kandidaat hun interesses en sterke punten te traceren. Nuttig voor het vinden van werk dat aansluit bij hun passies.",
  },
  {
    id: "e18",
    text: "Wat is iets dat je graag leert of al lang wil leren?",
    difficulty: "easy",
    category: "Ontwikkeling",
    guidance: "Dit toont groeimentaliteit en intrinsieke motivatie. Werkgevers waarderen kandidaten die willen leren en zich willen ontwikkelen.",
  },
  {
    id: "e19",
    text: "Hoe ziet een goede werkdag er voor jou concreet uit?",
    difficulty: "easy",
    category: "Werkstijl",
    guidance: "Dit helpt de kandidaat hun ideale werkdag te visualiseren en dit met werkgevers te bespreken. Nuttig voor het vinden van passend werk.",
  },
  {
    id: "e20",
    text: "Wat geeft jou het gevoel dat je ergens bij hoort op de werkvloer?",
    difficulty: "easy",
    category: "Werksfeer",
    guidance: "Dit onthult wat de kandidaat nodig heeft om zich welkom en geaccepteerd te voelen. Essentieel voor werkplezier en retentie.",
  },
  {
    id: "e21",
    text: "Wat is iets kleins dat je collega's meteen over jou mogen weten?",
    difficulty: "easy",
    category: "Zelfpresentatie",
    guidance: "Dit helpt de kandidaat een authentieke en positieve zelfpresentatie te oefenen. Nuttig voor het opbouwen van relaties op het werk.",
  },
  {
    id: "e22",
    text: "Wat zou je doen als je een vrije dag hebt en geen verplichtingen?",
    difficulty: "easy",
    category: "Zelfkennis",
    guidance: "Dit onthult wat de kandidaat werkelijk motiveert en wat hun passies zijn. Nuttig voor het vinden van betekenisvol werk.",
  },
];

export const mediumQuestions: Question[] = [
  {
    id: "m1",
    text: "Waarin maak jij het meeste verschil in een team, denk je?",
    difficulty: "medium",
    category: "Sterktes",
    tip: "Peilt naar zelfinzicht en het vermogen om de eigen bijdrage te benoemen.",
    guidance: "Dit helpt de kandidaat hun unieke waarde in te zien en dit in sollicitatiegesprekken te communiceren. Belangrijk voor zelfvertrouwen.",
  },
  {
    id: "m2",
    text: "Hoe ga je om met feedback die je eerst wat lastig vindt om te horen?",
    difficulty: "medium",
    category: "Feedback",
    tip: "Typische sollicitatievraag. Laat de kandidaat een concreet voorbeeld geven.",
    guidance: "Dit is een klassieke sollicitatievraag. Het toont of de kandidaat open staat voor groei en kan omgaan met kritiek op een constructieve manier.",
  },
  {
    id: "m3",
    text: "In welke situatie heb je onlangs echt uit je comfortzone moeten komen?",
    difficulty: "medium",
    category: "Groei",
    guidance: "Dit toont groeimentaliteit en veerkracht. Werkgevers willen zien dat kandidaten kunnen groeien en zich kunnen aanpassen aan nieuwe situaties.",
  },
  {
    id: "m4",
    text: "Wat heb je geleerd uit een fout die je zelf ooit op school of werk hebt gemaakt?",
    difficulty: "medium",
    category: "Zelfreflectie",
    tip: "Toont of de kandidaat kan leren van fouten zonder zichzelf te veroordelen.",
    guidance: "Dit toont zelfreflectie en het vermogen om van fouten te leren. Werkgevers waarderen kandidaten die verantwoordelijkheid nemen en groeien.",
  },
  {
    id: "m5",
    text: "Hoe merk je aan jezelf dat je te veel hooi op je vork neemt, en wat doe je dan?",
    difficulty: "medium",
    category: "Zelfregulatie",
    guidance: "Dit helpt de kandidaat hun grenzen te begrijpen en zelfregulatie te oefenen. Essentieel voor duurzame inzetbaarheid en burnout-preventie.",
  },
  {
    id: "m6",
    text: "Welke drie waarden wil je sowieso terugvinden bij een toekomstige werkgever?",
    difficulty: "medium",
    category: "Jobwensen",
    tip: "Helpt de kandidaat om bewuste keuzes te maken bij het zoeken naar werk.",
    guidance: "Dit helpt de kandidaat hun prioriteiten te verduidelijken en bewuste keuzes te maken. Werkgevers waarderen kandidaten met duidelijke waarden.",
  },
  {
    id: "m7",
    text: "Hoe ga je om met stress vlak voor een belangrijke deadline of evaluatie?",
    difficulty: "medium",
    category: "Stressbestendigheid",
    guidance: "Dit toont stressbestendigheid en copingstrategieën. Werkgevers willen zien dat kandidaten onder druk kunnen functioneren.",
  },
  {
    id: "m8",
    text: "Welke rol neem je meestal spontaan op in een groep?",
    difficulty: "medium",
    category: "Samenwerking",
    guidance: "Dit onthult natuurlijke teamrollen en leiderschapsstijl. Nuttig voor het vinden van passende teamposities.",
  },
  {
    id: "m9",
    text: "Wat is een talent of kwaliteit waarvan jij vindt dat die nog te weinig gezien wordt?",
    difficulty: "medium",
    category: "Sterktes",
    tip: "Geeft de kandidaat de kans om verborgen talenten te benoemen.",
    guidance: "Dit helpt de kandidaat verborgen talenten te erkennen en deze in sollicitatiegesprekken naar voren te brengen. Goed voor zelfvertrouwen.",
  },
  {
    id: "m10",
    text: "Wanneer heb je voor het laatst bewust om hulp gevraagd, en hoe liep dat af?",
    difficulty: "medium",
    category: "Samenwerking",
    guidance: "Dit toont of de kandidaat kan samenwerken en om hulp kan vragen. Belangrijk voor teamwork en het voorkomen van overbelasting.",
  },
  {
    id: "m11",
    text: "Wat vind je moeilijker: iemand aanspreken op gedrag of zelf aangesproken worden?",
    difficulty: "medium",
    category: "Communicatie",
    guidance: "Dit toont communicatievaardigheden en assertiviteit. Nuttig voor het begrijpen van hoe de kandidaat feedback geeft en ontvangt.",
  },
  {
    id: "m12",
    text: "Hoe ga je om met iemand in het team die heel anders werkt dan jij?",
    difficulty: "medium",
    category: "Samenwerking",
    guidance: "Dit toont flexibiliteit en respect voor diversiteit. Werkgevers waarderen kandidaten die goed kunnen samenwerken met verschillende persoonlijkheidstypes.",
  },
  {
    id: "m13",
    text: "Aan welk advies van een mentor, leerkracht of collega heb je nog vaak iets?",
    difficulty: "medium",
    category: "Zelfreflectie",
    guidance: "Dit toont dat de kandidaat open staat voor begeleiding en advies. Nuttig voor het begrijpen van hun leerbereidheid en groeimentaliteit.",
  },
  {
    id: "m14",
    text: "Wanneer voelt werk voor jou echt zinvol?",
    difficulty: "medium",
    category: "Motivatie",
    guidance: "Dit onthult wat de kandidaat werkelijk motiveert en wat zinvol voor hen is. Essentieel voor het vinden van betekenisvol werk.",
  },
  {
    id: "m15",
    text: "Waar wil jij binnen een paar jaar vooral in gegroeid zijn?",
    difficulty: "medium",
    category: "Toekomst",
    tip: "Klassieke sollicitatievraag. Laat de kandidaat realistisch en concreet nadenken.",
    guidance: "Dit is een klassieke sollicitatievraag. Het toont ambitie en het vermogen om realistische doelen te stellen. Werkgevers waarderen kandidaten met duidelijke groeiplannen.",
  },
  {
    id: "m16",
    text: "Hoe beslis je of je 'ja' of 'nee' zegt tegen een nieuwe kans of project?",
    difficulty: "medium",
    category: "Besluitvorming",
    guidance: "Dit toont besluitvormingsproces en grenzenstellingsvermogen. Nuttig voor het begrijpen van hoe de kandidaat prioriteiten stelt.",
  },
  {
    id: "m17",
    text: "Welke gewoonte wil je graag verder ontwikkelen om professioneler te worden?",
    difficulty: "medium",
    category: "Ontwikkeling",
    guidance: "Dit toont groeimentaliteit en zelfbewustzijn. Werkgevers waarderen kandidaten die willen groeien en zich willen verbeteren.",
  },
  {
    id: "m18",
    text: "Wat heb je gedaan om je voor te bereiden op je huidige zoektocht naar werk?",
    difficulty: "medium",
    category: "Jobzoeken",
    tip: "Peilt naar proactiviteit en zelfredzaamheid.",
    guidance: "Dit toont proactiviteit en voorbereiding. Werkgevers waarderen kandidaten die serieus werk maken van hun jobzoektocht.",
  },
  {
    id: "m19",
    text: "Welke professionele uitdaging heeft jou het meest gevormd tot wie je nu bent?",
    difficulty: "medium",
    category: "Zelfreflectie",
    guidance: "Dit toont zelfreflectie en hoe de kandidaat van ervaringen leert. Werkgevers waarderen kandidaten die van uitdagingen groeien.",
  },
  {
    id: "m20",
    text: "Wat vind jij belangrijker: jezelf blijven of je aanpassen aan het team, en waarom?",
    difficulty: "medium",
    category: "Werkstijl",
    guidance: "Dit toont waarden en flexibiliteit. Dit is belangrijk voor het begrijpen van hoe de kandidaat balans vindt tussen authenticiteit en teamwerk.",
  },
  {
    id: "m21",
    text: "Hoe reageer je als een taak veel moeilijker blijkt dan verwacht?",
    difficulty: "medium",
    category: "Stressbestendigheid",
    guidance: "Dit toont probleemoplossing en veerkracht. Werkgevers willen zien dat kandidaten kunnen omgaan met onverwachte uitdagingen.",
  },
  {
    id: "m22",
    text: "Wat zou je doen als je merkt dat je ergens niet goed in bent, maar het wel nodig is voor je job?",
    difficulty: "medium",
    category: "Ontwikkeling",
    guidance: "Dit toont groeimentaliteit en het vermogen om zwakke punten aan te pakken. Werkgevers waarderen kandidaten die willen leren en groeien.",
  },
];

export const hardQuestions: Question[] = [
  {
    id: "h1",
    text: "Wat zou jij doen als je merkt dat een collega systematisch te laat komt maar wel hard werkt?",
    difficulty: "hard",
    category: "Dilemma's",
    tip: "Toont hoe de kandidaat omgaat met conflicten en grenzen op de werkvloer.",
    guidance: "Dit dilemma toont hoe de kandidaat omgaat met conflicten, grenzen en ethiek. Werkgevers willen zien dat kandidaten kunnen communiceren en grenzen kunnen stellen.",
  },
  {
    id: "h2",
    text: "Stel dat je een fout ontdekt in een project dat bijna opgeleverd wordt: wat doe je?",
    difficulty: "hard",
    category: "Integriteit",
    guidance: "Dit toont integriteit en verantwoordelijkheid. Werkgevers willen zien dat kandidaten het juiste doen, zelfs als het moeilijk is.",
  },
  {
    id: "h3",
    text: "Hoe ga je om met een leidinggevende waarmee je fundamenteel oneens bent?",
    difficulty: "hard",
    category: "Gezag & Autonomie",
    tip: "Peilt naar assertiviteit én respect voor hiërarchie.",
    guidance: "Dit toont hoe de kandidaat omgaat met gezagsconflicten. Werkgevers willen zien dat kandidaten assertief kunnen zijn terwijl ze respect tonen.",
  },
  {
    id: "h4",
    text: "Wat weegt voor jou zwaarder: eerlijkheid of loyaliteit, als die twee botsen?",
    difficulty: "hard",
    category: "Waarden",
    guidance: "Dit toont kernwaarden en moreel kompas. Dit helpt werkgevers begrijpen wat de kandidaat echt belangrijk vindt.",
  },
  {
    id: "h5",
    text: "Is het oké om iets positief voor te stellen in een sollicitatie terwijl je weet dat je daar nog niet sterk in bent?",
    difficulty: "hard",
    category: "Integriteit",
    tip: "Goed startpunt voor een gesprek over eerlijkheid versus zelfpromotie.",
    guidance: "Dit toont hoe de kandidaat omgaat met integriteit versus zelfpromotie. Werkgevers waarderen eerlijkheid en authentieke zelfpresentatie.",
  },
  {
    id: "h6",
    text: "Waar ligt voor jou de grens tussen een grapje op het werk en ongepast gedrag?",
    difficulty: "hard",
    category: "Werksfeer",
    guidance: "Dit toont grenzenstellingsvermogen en respect voor anderen. Werkgevers willen zien dat kandidaten professioneel kunnen zijn.",
  },
  {
    id: "h7",
    text: "Wat zou je doen als je merkt dat iemand anders erkenning krijgt voor jouw idee?",
    difficulty: "hard",
    category: "Assertiviteit",
    guidance: "Dit toont assertiviteit en zelfverdediging. Werkgevers willen zien dat kandidaten voor zichzelf opkomen op een professionele manier.",
  },
  {
    id: "h8",
    text: "Hoe reageer je als je gevraagd wordt om 'een beetje te verzwijgen' tegenover een klant of collega?",
    difficulty: "hard",
    category: "Integriteit",
    guidance: "Dit toont integriteit en grenzenstellingsvermogen. Werkgevers willen zien dat kandidaten niet meewerken aan oneerlijkheid.",
  },
  {
    id: "h9",
    text: "Wat doe je als je in een team de enige bent met een andere mening over een belangrijke beslissing?",
    difficulty: "hard",
    category: "Assertiviteit",
    guidance: "Dit toont assertiviteit en het vermogen om voor je mening uit te komen. Werkgevers waarderen kandidaten die kritisch kunnen denken.",
  },
  {
    id: "h10",
    text: "Is het ooit oké om een jobaanbod te aanvaarden terwijl je eigenlijk nog twijfelt, en waarom?",
    difficulty: "hard",
    category: "Besluitvorming",
    guidance: "Dit toont besluitvormingsvermogen en integriteit. Werkgevers willen zien dat kandidaten bewuste keuzes maken.",
  },
  {
    id: "h11",
    text: "Wat zou je doen als je ziet dat iemand op de werkvloer duidelijk onrechtvaardig behandeld wordt?",
    difficulty: "hard",
    category: "Rechtvaardigheid",
    tip: "Toont empathie, moed en inzicht in sociale dynamieken.",
    guidance: "Dit toont empathie, moed en moreel kompas. Werkgevers waarderen kandidaten die voor anderen opkomen.",
  },
  {
    id: "h12",
    text: "Wat vind jij moeilijker: toegeven dat je iets niet weet of toegeven dat je ongelijk had?",
    difficulty: "hard",
    category: "Zelfreflectie",
    guidance: "Dit toont zelfreflectie en het vermogen om verantwoordelijkheid te nemen. Werkgevers waarderen bescheidenheid en leerbereidheid.",
  },
  {
    id: "h13",
    text: "Wat betekent integriteit voor jou in een job, heel concreet?",
    difficulty: "hard",
    category: "Waarden",
    guidance: "Dit toont kernwaarden en moreel kompas. Dit helpt werkgevers begrijpen wat integriteit voor de kandidaat betekent.",
  },
  {
    id: "h14",
    text: "Zou je liever werken in een bedrijf dat sterke waarden heeft maar minder betaalt, of omgekeerd?",
    difficulty: "hard",
    category: "Waarden",
    guidance: "Dit toont prioriteiten en waarden. Dit helpt werkgevers begrijpen wat de kandidaat werkelijk belangrijk vindt.",
  },
  {
    id: "h15",
    text: "Wanneer vind jij dat je 'te ver' gaat om een doel te halen op het werk?",
    difficulty: "hard",
    category: "Grenzen",
    guidance: "Dit toont grenzenstellingsvermogen en integriteit. Werkgevers willen zien dat kandidaten gezonde grenzen kunnen stellen.",
  },
  {
    id: "h16",
    text: "Hoe ver mag een werkgever gaan in het controleren van medewerkers, volgens jou?",
    difficulty: "hard",
    category: "Rechten & Plichten",
    guidance: "Dit toont kennis van werknemersrechten en privacy. Werkgevers willen zien dat kandidaten hun rechten kennen.",
  },
  {
    id: "h17",
    text: "Wanneer mag je volgens jou 'nee' zeggen tegen een opdracht, zelfs als het dringend is?",
    difficulty: "hard",
    category: "Grenzen",
    tip: "Belangrijk voor kandidaten die moeite hebben met grenzen stellen.",
    guidance: "Dit toont grenzenstellingsvermogen en zelfbescherming. Werkgevers willen zien dat kandidaten gezonde grenzen kunnen stellen.",
  },
  {
    id: "h18",
    text: "Welk dilemma zou jij zeker willen bespreken met een toekomstige leidinggevende?",
    difficulty: "hard",
    category: "Openheid",
    guidance: "Dit toont openheid en het vermogen om moeilijke onderwerpen aan te snijden. Werkgevers waarderen kandidaten die proactief communiceren.",
  },
  {
    id: "h19",
    text: "Stel dat je beperking of gezondheidssituatie invloed heeft op je werk: hoe en wanneer vertel je dat aan een werkgever?",
    difficulty: "hard",
    category: "Zelfonthulling",
    tip: "Zeer relevant voor GTB-kandidaten. Bespreek openheid, timing en formulering.",
    guidance: "Dit is een kernvraag voor GTB-kandidaten. Het helpt de kandidaat na te denken over timing, formulering en strategie bij het delen van hun situatie.",
  },
  {
    id: "h20",
    text: "Wat doe je als je merkt dat de aanpassingen die je nodig hebt op de werkvloer niet worden gerespecteerd?",
    difficulty: "hard",
    category: "Rechten & Plichten",
    tip: "Peilt naar assertiviteit en kennis van rechten als werknemer met een beperking.",
    guidance: "Dit is cruciaal voor GTB-kandidaten. Het toont assertiviteit en kennis van werknemersrechten. Werkgevers willen zien dat kandidaten voor zichzelf opkomen.",
  },
  {
    id: "h21",
    text: "Hoe beslis je of je eerlijk bent over je beperkingen in een sollicitatiegesprek?",
    difficulty: "hard",
    category: "Zelfonthulling",
    tip: "Kernvraag voor GTB-trajecten. Laat de kandidaat nadenken over strategie en authenticiteit.",
    guidance: "Dit is een kernvraag voor GTB-kandidaten. Het helpt de kandidaat na te denken over balans tussen eerlijkheid en zelfbescherming.",
  },
  {
    id: "h22",
    text: "Wat zou je doen als een werkgever je vraagt om iets te doen wat ingaat tegen je waarden of gezondheid?",
    difficulty: "hard",
    category: "Grenzen",
    guidance: "Dit toont grenzenstellingsvermogen en zelfbescherming. Werkgevers willen zien dat kandidaten gezonde grenzen kunnen stellen.",
  },
];

export const allQuestions = [...easyQuestions, ...mediumQuestions, ...hardQuestions];

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  easy: "Makkelijk",
  medium: "Gemiddeld",
  hard: "Moeilijk",
};

export const DIFFICULTY_COLORS: Record<Difficulty, string> = {
  easy: "#10b981",
  medium: "#f59e0b",
  hard: "#ef4444",
};

export const DIFFICULTY_BG: Record<Difficulty, string> = {
  easy: "#d1fae5",
  medium: "#fef3c7",
  hard: "#fee2e2",
};
